import requests
import streamlit as st

st.set_page_config(layout="wide")
st.title("Camera input demo app. Take photo and see it toonified!")

col_left, _, col_right = st.columns([5, 1, 4])


def camera_input_on_change():
    with col_right:
        if st.session_state.camera_input_file:
            with st.spinner("Processing..."):
                r = requests.post(
                    "https://api.deepai.org/api/toonify",
                    files={"image": st.session_state.camera_input_file},
                    headers={"api-key": st.secrets.api_key},
                )
                st.text("")
                if r.status_code == 200:
                    response = r.json()
                    st.image(response["output_url"])
                    st.caption(
                        "Image generated by [Toonify](https://deepai.org/machine-learning-model/toonify)"
                    )
                else:
                    st.write(
                        "An error occurred processing your input. Please check your input and try again."
                    )


with col_left:
    st.camera_input(label="", key="camera_input_file", on_change=camera_input_on_change)